/**
 * A small deterministic TOML emitter — the byte contract the two inputs-template
 * projections share. Exact mirror of `mthds/protocol/toml_emitter.py`.
 *
 * A projected inputs template is TOML text as well as a JSON object, and the two
 * projections — this one and the Python twin in the `mthds` PyPI package — must
 * produce the *same bytes*, the `# concept: …` comment lines included. Neither
 * language's TOML library can be handed that job: `smol-toml` emits no comments
 * at all, and a library's layout choices are its own to change in a patch
 * release, on its own schedule, in one language and not the other. So the layout
 * is written out here, in the few dozen lines it takes, and mirrored line for
 * line on the other side; `tests/fixtures/protocol/inputs_template/` is the
 * corpus that holds the two to it.
 *
 * Two layouts, because a template has two shapes:
 *
 * - **The table layout** ({@link renderTableLayout}) — what the explicit
 *   `{concept, content}` shape takes. Every top-level value in it is a table, so
 *   the plain sectioned layout is both valid and readable.
 * - **The inline layout** ({@link renderInlineLayout}) — what the compact shape
 *   takes. A compact template interleaves bare top-level scalars with structured
 *   values, so every value stays at the top level as an inline table: authored
 *   order survives, a trailing scalar is not swallowed into the section above it,
 *   and each key can carry its own `# concept: …` line.
 *
 * The rules the table layout follows, which is the part a library would
 * otherwise be deciding:
 *
 * - A table states its scalar members first, in authored order, then its table
 *   members, also in authored order. TOML cannot interleave a section with the
 *   keys of its parent, so the split itself is forced; keeping each half in
 *   authored order is the choice.
 * - A table whose members are *all* tables states no header of its own — its
 *   children carry the whole dotted path (`[page_in.content.text_and_images]`).
 *   An empty table is not one of those: it has no child to carry its path, so it
 *   states its header and stands alone.
 * - A non-empty list of tables is an array of tables: one `[[dotted.path]]`
 *   header per element, and an element always states its header, even when every
 *   one of its own members is a table.
 * - Exactly one blank line before every header, and none before the first line of
 *   the document.
 *
 * A comment is one line by construction, and the emitter refuses one that is not.
 * It is the only text that reaches the document unquoted — every key is spelled
 * as a key and every value as a value — so a line terminator inside it would not
 * corrupt the comment but end it, and turn whatever followed into live TOML. The
 * comment text is built from `concept_ref`, which the descriptor types carry as
 * an unconstrained `string` from whatever producer emitted the artifact, so the
 * emitter states the rule here rather than trusting the producer for it.
 *
 * TOML has no null. A `null` is written as an empty string rather than dropped,
 * so the key stays visible to whoever fills the template in — an omitted key
 * reads as a field the method never declared.
 *
 * **The one thing this side needs that Python does not: {@link TemplateFloat}.**
 * Python spells `0` and `0.0` apart because it has two numeric types;
 * TypeScript has one, so a template's non-integer placeholder would print as `0`
 * and break byte parity on the very first `price` field. A number that must keep
 * its decimal point is therefore carried as a `TemplateFloat`, and this module —
 * which owns how a scalar is spelled — is where that marker and its spelling
 * live, for the TOML layouts here and for the JSON writer in `inputs_template.ts`
 * alike.
 *
 * The blank-line rule is applied uniformly here, and `tomlkit` — which the corpus
 * generator in `pipelex` still renders through — does not apply it uniformly. It
 * omits the blank line before an array-of-tables that is the first member of its
 * container (`{"items": [{"a": 1}], "label": "x"}` → `label = "x"\n[[items]]`),
 * and before the first table-ish member of an array-of-tables element
 * (`{"outer": [{"inner": [{"a": 1}]}]}` → `[[outer]]\n[[outer.inner]]`), because
 * its trivia bookkeeping records the newline on a wrapper its own array renderer
 * never reads. It also reorders a mapping's members when that mapping is an
 * element of a list, sorting mapping-valued members last. The committed corpus
 * exercises none of those shapes, so the two agree on every byte of it today —
 * but a bundle added to the corpus could reach them, and the regenerated bytes
 * would then carry the inconsistency and fail both projections at once. The fix
 * is for the generator to render through this contract rather than through a TOML
 * library; `L-260831-4031a7` tracks it in `pipelex`.
 */

/** A key TOML spells bare: letters, digits, `-` and `_`, and at least one of them. */
const BARE_KEY = /^[A-Za-z0-9_-]+$/;

/** The escapes a TOML basic string spells compactly; every other control character takes `\uXXXX`. */
const COMPACT_ESCAPES: Record<string, string> = {
  "\b": "\\b",
  "\t": "\\t",
  "\n": "\\n",
  "\f": "\\f",
  "\r": "\\r",
  '"': '\\"',
  "\\": "\\\\",
};

const TRUE = "true";
const FALSE = "false";

/**
 * A number that must print with its decimal point — the JS-only half of the byte
 * contract, and the reason a projected template is not a plain JSON value tree.
 *
 * `toJSON` unwraps it, so `JSON.stringify` over a projected template still yields
 * valid JSON; it yields `0` where the corpus says `0.0`, which is exactly why the
 * projection renders JSON through its own writer rather than through
 * `JSON.stringify`.
 */
export class TemplateFloat {
  constructor(readonly value: number) {}

  toJSON(): number {
    return this.value;
  }
}

/** A table of a projected template: keys in authored order, values of any template shape. */
export interface TemplateTable {
  [key: string]: TemplateValue;
}

/** Any value a projected template can hold, and therefore any value this emitter can spell. */
export type TemplateValue =
  | string
  | number
  | boolean
  | null
  | TemplateFloat
  | TemplateValue[]
  | TemplateTable;

/**
 * A value the emitter has no TOML spelling for reached it.
 *
 * The projection builds every value it emits, so this is a programming error
 * rather than bad input — the one exception being a comment carrying a character
 * a TOML comment cannot hold, which comes from a producer's `concept_ref`.
 */
export class TomlEmissionError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "TomlEmissionError";
  }
}

/**
 * Render a template whose values are all tables, as sectioned TOML.
 *
 * @param template - The template, one entry per declared input slot, in authored order.
 * @returns The TOML text, ending in exactly one newline; the empty string for an empty template.
 */
export function renderTableLayout(template: TemplateTable): string {
  const lines: string[] = [];
  emitMembers(substituteNulls(template) as TemplateTable, [], lines);
  return join(lines);
}

/**
 * Render a template as top-level keys carrying inline values, each optionally commented.
 *
 * @param template - The template, one entry per declared input slot, in authored order.
 * @param comments - Per-key comment text, without its leading `# `. A key with no
 *   entry takes no comment line, and one carrying a line terminator or any other
 *   control character is refused rather than written into the document.
 * @returns The TOML text, ending in exactly one newline; the empty string for an empty template.
 * @throws {TomlEmissionError} A comment carries a character a TOML comment cannot hold.
 */
export function renderInlineLayout(
  template: TemplateTable,
  comments: Record<string, string>,
): string {
  const lines: string[] = [];
  for (const [key, value] of Object.entries(substituteNulls(template) as TemplateTable)) {
    const commentText = comments[key];
    if (commentText) {
      lines.push(`# ${checkedComment(commentText, key)}`);
    }
    lines.push(`${renderKey(key)} = ${renderInlineValue(value)}`);
  }
  return join(lines);
}

/**
 * One scalar number, spelled as both TOML and JSON spell it — the shared rule, so
 * the two serializations of one template cannot disagree about a decimal point.
 */
export function spellNumber(value: number | TemplateFloat): string {
  if (value instanceof TemplateFloat) {
    return Number.isInteger(value.value) ? `${value.value}.0` : String(value.value);
  }
  return String(value);
}

/**
 * The comment text, refused when it carries a character a TOML comment cannot hold.
 *
 * A comment is unquoted and runs to the end of its line, so a line terminator
 * inside it does not corrupt the comment — it ends it, and what follows becomes a
 * line of the document in its own right. Refusing is what the emitter does with a
 * value it has no spelling for, and this is the same fact about the same document.
 */
function checkedComment(text: string, key: string): string {
  for (const character of text) {
    if (isCommentForbidden(character)) {
      const codePoint = character.charCodeAt(0).toString(16).padStart(4, "0");
      throw new TomlEmissionError(
        `The comment on key '${key}' carries '\\u${codePoint}', which a TOML comment cannot hold`,
      );
    }
  }
  return text;
}

/** One newline after every line, and nothing at all for a document with no lines. */
function join(lines: string[]): string {
  if (lines.length === 0) return "";
  return `${lines.join("\n")}\n`;
}

/** Replace every `null` with an empty string, recursively — TOML has no null. */
function substituteNulls(value: TemplateValue): TemplateValue {
  if (value === null) return "";
  if (Array.isArray(value)) return value.map((element) => substituteNulls(element));
  if (isTable(value)) {
    return Object.fromEntries(
      Object.entries(value).map(([key, member]) => [key, substituteNulls(member)]),
    );
  }
  return value;
}

/** Whether a value is a table — a mapping, which a {@link TemplateFloat} deliberately is not. */
function isTable(value: TemplateValue): value is TemplateTable {
  return (
    typeof value === "object" &&
    value !== null &&
    !Array.isArray(value) &&
    !(value instanceof TemplateFloat)
  );
}

/**
 * Whether a value takes a section of its own rather than a `key = value` line.
 *
 * A mapping always does. A list does exactly when it is a non-empty list of
 * mappings — an array of tables; a list of scalars, a mixed list and an empty list
 * are all inline arrays.
 */
function isTableValue(value: TemplateValue): boolean {
  if (isTable(value)) return true;
  if (Array.isArray(value)) return value.length > 0 && value.every((element) => isTable(element));
  return false;
}

/**
 * Whether a table states no header of its own, leaving its children to carry the dotted path.
 *
 * Non-empty and nothing but tables inside. An empty table is deliberately not one:
 * it has no child to state the path, so a header is the only thing that puts it in
 * the document at all.
 */
function isSuperTable(table: TemplateTable): boolean {
  const members = Object.values(table);
  if (members.length === 0) return false;
  return members.every((value) => isTableValue(value));
}

/** Emit one table's body: its scalar members first, in authored order, then its table members. */
function emitMembers(table: TemplateTable, path: readonly string[], lines: string[]): void {
  const tableMembers: [string, TemplateValue][] = [];
  for (const [key, value] of Object.entries(table)) {
    if (isTableValue(value)) {
      tableMembers.push([key, value]);
    } else {
      lines.push(`${renderKey(key)} = ${renderInlineValue(value)}`);
    }
  }
  for (const [key, value] of tableMembers) {
    const memberPath = [...path, key];
    if (Array.isArray(value)) {
      for (const element of value) {
        emitTable(element as TemplateTable, memberPath, lines, true);
      }
    } else {
      emitTable(value as TemplateTable, memberPath, lines, false);
    }
  }
}

/** Emit one table, with its header unless it is a super table, then its body. */
function emitTable(
  table: TemplateTable,
  path: readonly string[],
  lines: string[],
  isArrayElement: boolean,
): void {
  if (isArrayElement || !isSuperTable(table)) {
    if (lines.length > 0) lines.push("");
    const [openMarker, closeMarker] = isArrayElement ? ["[[", "]]"] : ["[", "]"];
    lines.push(`${openMarker}${renderPath(path)}${closeMarker}`);
  }
  emitMembers(table, path, lines);
}

/** The dotted header path, each segment spelled the way a key is. */
function renderPath(path: readonly string[]): string {
  return path.map((segment) => renderKey(segment)).join(".");
}

/** A bare key where TOML allows one, a quoted key otherwise — a dotted input name included. */
function renderKey(key: string): string {
  if (BARE_KEY.test(key)) return key;
  return renderString(key);
}

/** One value on a single line: an inline table, an inline array, or a scalar. */
function renderInlineValue(value: TemplateValue): string {
  if (isTable(value)) {
    const rendered = Object.entries(value)
      .map(([key, member]) => `${renderKey(key)} = ${renderInlineValue(member)}`)
      .join(", ");
    return `{${rendered}}`;
  }
  if (Array.isArray(value)) {
    return `[${value.map((element) => renderInlineValue(element)).join(", ")}]`;
  }
  return renderScalar(value);
}

/** One scalar, spelled as TOML spells it. */
function renderScalar(value: string | number | boolean | null | TemplateFloat): string {
  if (typeof value === "boolean") return value ? TRUE : FALSE;
  if (typeof value === "number" || value instanceof TemplateFloat) return spellNumber(value);
  if (typeof value === "string") return renderString(value);
  throw new TomlEmissionError(`No TOML spelling for a value of type '${typeof value}'`);
}

/** A basic string: the compact escapes where there is one, `\uXXXX` for any other control character. */
function renderString(text: string): string {
  let escaped = "";
  for (const character of text) {
    const compact = COMPACT_ESCAPES[character];
    if (compact !== undefined) {
      escaped += compact;
    } else if (isControl(character)) {
      escaped += `\\u${character.charCodeAt(0).toString(16).padStart(4, "0")}`;
    } else {
      escaped += character;
    }
  }
  return `"${escaped}"`;
}

/** The C0 control characters and DEL — what a basic string escapes. */
function isControl(character: string): boolean {
  const code = character.charCodeAt(0);
  return code < 0x20 || code === 0x7f;
}

/**
 * A comment runs to the end of its line and admits no control character but a tab,
 * so these are the characters a comment cannot carry: the line terminators end it,
 * and the rest TOML does not allow.
 */
function isCommentForbidden(character: string): boolean {
  return isControl(character) && character !== "\t";
}
